SET IDENTITY_INSERT Role ON;
IF NOT EXISTS (SELECT 1 FROM Role WHERE roleId = 1)
    INSERT INTO Role (roleId, nome) VALUES (1, 'ADMIN');

IF NOT EXISTS (SELECT 1 FROM Role WHERE roleId = 2)
    INSERT INTO Role (roleId, nome) VALUES (2, 'BASIC');

SET IDENTITY_INSERT Role OFF;